//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time_Keeper
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogEntry
    {
        public long ID { get; set; }
        public string ProgramName { get; set; }
        public System.DateTime In { get; set; }
        public Nullable<System.DateTime> Out { get; set; }
        public Nullable<double> Hours { get; set; }
        public System.DateTime Date { get; set; }
    }
}
