//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time_Keeper
{
    using System;
    using System.Collections.Generic;
    
    public partial class Programs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Programs()
        {
            this.Entries = new HashSet<Entries>();
            this.Totals = new HashSet<Totals>();
        }
    
        public int ProgramID { get; set; }
        public string Name { get; set; }
        public int Order { get; set; }
        public string Code { get; set; }
        public string Notes { get; set; }
        public Nullable<int> EntryID { get; set; }
        public Nullable<int> TotalID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Entries> Entries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Totals> Totals { get; set; }
    }
}
