//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time_Keeper
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TimeKeeperDBEntities : DbContext
    {
        public TimeKeeperDBEntities()
            : base("name=TimeKeeperDBEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Dates> Dates { get; set; }
        public virtual DbSet<Programs> Programs { get; set; }
        public virtual DbSet<Totals> Totals { get; set; }
        public virtual DbSet<Entries> Entries { get; set; }
    }
}
