//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time_Keeper
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TimeKeeperDBEntities : DbContext
    {
        public TimeKeeperDBEntities()
            : base()
        {
            this.Configuration.LazyLoadingEnabled = false;
        }

        public DbSet<Dates> Dates { get; set; }
        public DbSet<Programs> Programs { get; set; }
        public DbSet<Totals> Totals { get; set; }
        public  DbSet<Entries> Entries { get; set; }
    }
}
