//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time_Keeper
{
    using System;
    using System.Collections.Generic;
    
    public partial class Totals
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Totals()
        {
            this.Dates = new HashSet<Dates>();
            this.Programs = new HashSet<Programs>();
        }
    
        public int TotalID { get; set; }
        public Nullable<decimal> Hours { get; set; }
        public string Comments { get; set; }
        public System.DateTime DateID { get; set; }
        public string ProgramName { get; set; }
    
        public virtual Dates Date { get; set; }
        public virtual Programs Program { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dates> Dates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Programs> Programs { get; set; }
    }
}
